import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        
       <NavBar></NavBar>
        
        {children}
        
        <footer>i am footer</footer>
        
        </body>
    </html>
  );
}
